"""2020_9_22 create_table

Revision ID: 69d7bf9cd0a3
Revises: 
Create Date: 2020-09-22 13:52:51.785822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69d7bf9cd0a3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('upload',
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('is_delete', sa.SmallInteger(), nullable=True, comment='删除标识'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('filename', sa.String(length=252), nullable=True, comment='文件名'),
    sa.Column('file_md5', sa.String(length=128), nullable=True, comment='文件md5'),
    sa.Column('file_type', sa.SmallInteger(), nullable=True, comment='文件类型'),
    sa.Column('file_size', sa.Integer(), nullable=True, comment='文件大小'),
    sa.Column('path', sa.String(length=256), nullable=True, comment='文件路径'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('is_delete', sa.SmallInteger(), nullable=True, comment='删除标识'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=16), nullable=False, comment='用户名'),
    sa.Column('password', sa.String(length=32), nullable=False, comment='密码'),
    sa.Column('encryption', sa.String(length=6), nullable=False, comment='密文'),
    sa.Column('nickname', sa.String(length=32), nullable=True, comment='昵称'),
    sa.Column('email', sa.String(length=128), nullable=True, comment='邮箱'),
    sa.Column('phone', sa.String(length=11), nullable=True, comment='手机号码'),
    sa.Column('superuser', sa.SmallInteger(), nullable=True, comment='后台用户,0否1是'),
    sa.Column('image_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['upload.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('upload')
    # ### end Alembic commands ###
