"""2020-10-23 article add description

Revision ID: 9183378b0144
Revises: e837f65e22a2
Create Date: 2020-10-23 10:32:52.435398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9183378b0144'
down_revision = 'e837f65e22a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('description', sa.String(length=255), nullable=True, comment='文章简要描述'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'description')
    # ### end Alembic commands ###
