"""2020_10_3 create_table

Revision ID: a535ad033de8
Revises: 74762d608e31
Create Date: 2020-10-03 12:22:36.819960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a535ad033de8'
down_revision = '74762d608e31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('picture_album',
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('is_delete', sa.SmallInteger(), nullable=True, comment='删除标识'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False, comment='图集名'),
    sa.Column('description', sa.Text(), nullable=True, comment='图集描述'),
    sa.Column('show', sa.SmallInteger(), nullable=True, comment='是否展示0否1是'),
    sa.Column('category_id', sa.Integer(), nullable=True, comment='栏目'),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('picture',
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('is_delete', sa.SmallInteger(), nullable=True, comment='删除标识'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=128), nullable=True, comment='标题'),
    sa.Column('description', sa.Text(), nullable=True, comment='描述'),
    sa.Column('url', sa.String(length=255), nullable=True, comment='跳转地址'),
    sa.Column('image_id', sa.Integer(), nullable=True),
    sa.Column('picture_album_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['upload.id'], ),
    sa.ForeignKeyConstraint(['picture_album_id'], ['picture_album.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('category', sa.Column('show', sa.SmallInteger(), nullable=True, comment='前台是否展示,0否1是'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category', 'show')
    op.drop_table('picture')
    op.drop_table('picture_album')
    # ### end Alembic commands ###
