"""2020_10_9 add field publish_date

Revision ID: e837f65e22a2
Revises: a535ad033de8
Create Date: 2020-10-09 20:12:25.356671

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e837f65e22a2'
down_revision = 'a535ad033de8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article',
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('is_delete', sa.SmallInteger(), nullable=True, comment='删除标识'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False, comment='文章标题'),
    sa.Column('content', sa.Text(), nullable=True, comment='文章内容'),
    sa.Column('comment', sa.Integer(), nullable=True, comment='评论人数'),
    sa.Column('agree', sa.Integer(), nullable=True, comment='点赞人数'),
    sa.Column('click', sa.Integer(), nullable=True, comment='浏览次数'),
    sa.Column('recom', sa.SmallInteger(), nullable=True, comment='是否推荐，0否1是'),
    sa.Column('published', sa.SmallInteger(), nullable=True, comment='是否发布0否1是'),
    sa.Column('publish_date', sa.DateTime(), nullable=False, comment='发布时间'),
    sa.Column('cover_id', sa.Integer(), nullable=True, comment='封面'),
    sa.Column('category_id', sa.Integer(), nullable=True, comment='栏目'),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['cover_id'], ['upload.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('artice')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artice',
    sa.Column('create_time', mysql.DATETIME(), nullable=False, comment='创建时间'),
    sa.Column('update_time', mysql.DATETIME(), nullable=False, comment='更新时间'),
    sa.Column('is_delete', mysql.SMALLINT(), autoincrement=False, nullable=True, comment='删除标识'),
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=255), nullable=False, comment='文章标题'),
    sa.Column('content', mysql.TEXT(), nullable=True, comment='文章内容'),
    sa.Column('comment', mysql.INTEGER(), autoincrement=False, nullable=True, comment='评论人数'),
    sa.Column('agree', mysql.INTEGER(), autoincrement=False, nullable=True, comment='点赞人数'),
    sa.Column('click', mysql.INTEGER(), autoincrement=False, nullable=True, comment='浏览次数'),
    sa.Column('recom', mysql.SMALLINT(), autoincrement=False, nullable=True, comment='是否推荐，0否1是'),
    sa.Column('published', mysql.SMALLINT(), autoincrement=False, nullable=True, comment='是否发布0否1是'),
    sa.Column('cover_id', mysql.INTEGER(), autoincrement=False, nullable=True, comment='封面'),
    sa.Column('category_id', mysql.INTEGER(), autoincrement=False, nullable=True, comment='栏目'),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], name='artice_ibfk_1'),
    sa.ForeignKeyConstraint(['cover_id'], ['upload.id'], name='artice_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('article')
    # ### end Alembic commands ###
